version: '3'
services:
  database:
    image: mongo:4.2.2
    volumes:
    - $PWD/scripts:/scripts
  api:
    image: api:${API_VERSION}
    environment:
    - MONGODB_URI=mongodb://database:27017/labtrail
    - JWT_SECRET=${JWT_SECRET}
    links:
    - "database:database"
  app:
    image: app:${APP_VERSION}
  qr:
    image: qr:${QR_VERSION}
  proxy:
    image: nginx:1.15-alpine
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "$PWD/etc/nginx/default.template:/etc/nginx/conf.d/default.template"
    - "$PWD/etc/nginx/localhost.crt:/etc/nginx/localhost.crt"
    - "$PWD/etc/nginx/localhost.key:/etc/nginx/localhost.key"
    links:
    - "api:api"
    - "app:app"
    - "qr:qr"
    environment:
    - NGINX_HOST=localhost
    command: /bin/ash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"