version: "3"
services:
  database:
    image: mongo:4.2.2
    volumes:
      - $PWD/scripts:/scripts
      - /usr/share/labtrail/database:/data/db
  api:
    image: docker.pkg.github.com/janikvonrotz/labtrail/api:${API_VERSION}
    environment:
      - MONGODB_URI=mongodb://database:27017/labtrail
      - JWT_SECRET=${JWT_SECRET}
    links:
      - "database:database"
  app:
    image: docker.pkg.github.com/janikvonrotz/labtrail/app:${APP_VERSION}
  qr:
    image: docker.pkg.github.com/janikvonrotz/labtrail/qr:${QR_VERSION}
    links:
      - "api:api"
  proxy:
    image: owasp/modsecurity:3-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/etc/modsecurity:/etc/modsecurity"
      - "$PWD/etc/modsecurity.d/include.conf:/etc/modsecurity.d/include.conf"
      - "$PWD/etc/modsecurity.d/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf"
      - "$PWD/etc/nginx/default.template:/etc/nginx/conf.d/default.template"
      - "$PWD/etc/nginx/localhost.crt:/etc/nginx/localhost.crt"
      - "$PWD/etc/nginx/localhost.key:/etc/nginx/localhost.key"
    links:
      - "api:api"
      - "app:app"
      - "qr:qr"
    environment:
      - NGINX_HOST=localhost
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
